### ISSUE TITLE
streaming interface

### ISSUE THREAD

**Issue by m-onz** [AcidLeroy/easy-doc-crypt#1]
I need to research this more but it seems to be from looking at the code that you encrypt the entire document at the same time.. this may fail with big files.

Would it be possible to make this into a streaming interface for big files. can you keep  pushing data somehow?.. There may be a different crypto primitive with libsodium for streaming (possibly secretstream)

This is pseudo code / example of what I mean with easy-doc-crypt as a transform stream for encryption

```js
var input = fs.createReadStream('./big_file.txt')
input.pipe(easy_doc_crypt.encrypt()).pipe(fs.createWriteStream('./output'))
```

I can have a go implementing this I was just asking in case you've already tried or had any thoughts.

**Comment by AcidLeroy** [comment]
@m-onz yeah this will definitely not work with big documents. There is a streaming interface already in the crypto stuff, but unfortunately the pre/post serialization stuff that I implemented this for (nedb or pouchdb) doesn't have a streaming API. So you basically have to have the entire document in memory in order to use this as a post/pre serialization adapter to these DBs. I think it would still be worth implementing a streaming API to this though as you mentioned.

**Comment by m-onz** [comment]
Cool, just as I thought.
